### ISSUE TITLE
error in compiler

### ISSUE THREAD

**Issue by b4zz4** [deater/ansi2gif#2]
ansi2gif.o: En la función `gif_the_text':
ansi2gif.c:(.text+0x491): referencia a`gdImageCreate' sin definir
ansi2gif.c:(.text+0x4aa): referencia a `gdImageCreate' sin definir
ansi2gif.c:(.text+0x4d4): referencia a`gdImageColorAllocate' sin definir
ansi2gif.c:(.text+0x4fe): referencia a `gdImageColorAllocate' sin definir
ansi2gif.c:(.text+0x528): referencia a`gdImageColorAllocate' sin definir
ansi2gif.c:(.text+0x552): referencia a `gdImageColorAllocate' sin definir
ansi2gif.c:(.text+0x57c): referencia a`gdImageColorAllocate' sin definir
ansi2gif.o:ansi2gif.c:(.text+0x5a6): más referencias a `gdImageColorAllocate' sin definir a continuación
ansi2gif.o: En la función`gif_the_text':
ansi2gif.c:(.text+0xa99): referencia a `gdImageRectangle' sin definir
ansi2gif.c:(.text+0xaaa): referencia a`gdImageGif' sin definir
ansi2gif.c:(.text+0xd0d): referencia a `gdImageSetPixel' sin definir
ansi2gif.c:(.text+0xd71): referencia a`gdImageGif' sin definir
ansi2gif.c:(.text+0xf8e): referencia a `gdImageSetPixel' sin definir
ansi2gif.c:(.text+0x102a): referencia a`gdImageGif' sin definir
ansi2gif.c:(.text+0x1109): referencia a `gdImageSetPixel' sin definir
ansi2gif.c:(.text+0x11d2): referencia a`gdImageGif' sin definir
ansi2gif.c:(.text+0x12e4): referencia a `gdImageDestroy' sin definir
ansi2gif.c:(.text+0x12f1): referencia a`gdImageDestroy' sin definir
ansi2gif.c:(.text+0x1ae4): referencia a `gdImagePng' sin definir
ansi2gif.c:(.text+0x1dce): referencia a`gdImageColorResolve' sin definir
ansi2gif.c:(.text+0x20fb): referencia a `gdImageColorResolve' sin definir
ansi2gif.c:(.text+0x2402): referencia a`gdImageGif' sin definir
ansi2gif.c:(.text+0x24da): referencia a `gdImageCreateTrueColor' sin definir
ansi2gif.c:(.text+0x24ff): referencia a`gdImageColorAllocate' sin definir
ansi2gif.c:(.text+0x252c): referencia a `gdImageRectangle' sin definir
ansi2gif.c:(.text+0x253d): referencia a`gdImageGif' sin definir
ansi2gif.c:(.text+0x2552): referencia a `gdImageDestroy' sin definir
ansi2gif.o: En la función`setup_gd_256colors':
ansi2gif.c:(.text.unlikely+0xb6): referencia a `gdImageColorAllocate' sin definir
ansi2gif.c:(.text.unlikely+0x136): referencia a`gdImageColorAllocate' sin definir
collect2: error: ld returned 1 exit status
make: **\* [ansi2gif] Error 1

**Comment by tim0s** [comment]
It seems you don't have all the depencencies installed. In particular you seem to be missing the gd library. If you are using debian or ubuntu, try apt-get install libgd-dev.

**Comment by b4zz4** [comment]
I installed the program, but just does not walk: S
thanks

El 11/06/15 a las 16:34, Timo Schneider escibió:

> It seems you don't have all the depencencies installed. In particular
> you seem to be missing the gd library. If you are using debian or
> ubuntu, try apt-get install libgd-dev.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/deater/ansi2gif/issues/2#issuecomment-111254719.

## 

http://ba.zza.pl
gpg: http://ba.zza.pl/bazza.asc
