### ISSUE TITLE
more explicit license

### ISSUE THREAD

**Issue by david-a-redick** [deater/ansi2gif#5]
The file below indicates that this is under the "GPL" license.  Can you put something more explicit in a header or README?

For example: "GNU GPL v1 only", "GNU GPL v2 or later" or "GNU GPL v3" and so forth.

https://github.com/deater/ansi2gif/blob/master/ansi2gif-0.11.0.lsm

Heh.  Even the LSM spec is vague: http://lsm.qqx.org/LSM.README

**Comment by deater** [comment]
yes, that wording in the LSM file probably dates back to 1999 when I first released things.

The original intention was GPLv2, I've added a COPYING file to clarify things.
